#define TYPE_RESSOURCE 1
#define TYPE_DEPOT 2
#define TYPE_DEVOIR 3
#define COMPTE_ATTENTE 0
#define COMPTE_ENSEIGNANT 1
#define COMPTE_ETUDIANT 2
#define COMPTE_ADMIN 3

// id de la vue connexion
#define ID_CONNEXION_MENUITEM_INSCRIPTION 101
#define ID_CONNEXION_BOUTON_CONNEXION 102
